apiVersion: v1
kind: Pod
metadata:
  name: dnspod
  namespace: default
spec:
  containers:
    - name: dnspod
      image: registry.k8s.io/e2e-test-images/jessie-dnspod:1.3
      command:
        - sleep
        - "infinity"
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
