apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          
          image: ds7000/cloud-computing:latest
          
          imagePullPolicy: "Always"
          ports:
            - containerPort: 5000
              name: webapp-int-port
          env:
            - name: PORT
              value: "5000"
            - name: FLASK
              value: development
            - name: MONGO_SERVICE
              value: "mongo-0.mongo-service.default.svc.cluster.local"
          resources:
            requests:
              memory: "128Mi"
              cpu: "0.5"
            limits:
              memory: "512Mi"
              cpu: "1"
          livenessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5


#----------------------
apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  selector:
    app: webapp
  ports:
    - port: 8080
      targetPort: 5000
      protocol: TCP
  type: LoadBalancer